import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Banner from 'components/banner/banner.component';
import Card from 'components/card/card.component';
import styles from 'styles/Home.module.css';

import coffeeStoresData from 'data/coffee-stores.json';

interface HomeProps {
  coffeeStores: typeof coffeeStoresData;
}

export const getStaticProps: GetStaticProps<HomeProps> = async (context) => {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
};

const Home: NextPage<HomeProps> = (props) => {
  const handleOnBannerBtnClick = () => {
    console.log('Hi banner button');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl}
                  href={`/coffee-store/${coffeeStore.id}`}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
